<!-- YOU CAN DELETE THIS FILE IF YOU LINKED WITH DATABASE -->
 
 
<?php
  $Allquestions = array (
   [
      'id' => 1 ,
      'question' => '________ clever people!' ,
      'option1' => 'What a' ,
      'option2' => 'What' ,
      'option3' => 'How' ,
      'option4' => 'So' ,
      'answer' => 'option2'
   ],
   [
      'id' => 2 ,
      'question' => '________ the homework. ' ,
      'option1' => 'No every students do' ,
      'option2' => 'No every students' ,
      'option3' => 'Not every students do' ,
      'option4' => 'Not every student does' ,
      'answer' => 'option4'
   ],
   [
      'id' => 3 ,
      'question' => 'Choose the correct answer. Only one answer is correct. ' ,
      'option1' => 'How is your age?' ,
      'option2' => 'How old are you?' ,
      'option3' => 'What age have you got?' ,
      'option4' => 'How many years you are?' ,
      'answer' => 'option2'
   ],
   [
      'id' => 4 ,
      'question' => 'Mary had ________ money.' ,
      'option1' => 'enough' ,
      'option2' => 'many' ,
      'option3' => 'fewer' ,
      'option4' => 'any' ,
      'answer' => 'option1',
   ],
   [
      'id' => 5 ,
      'question' => 'What ________ on Sundays?' ,
      'option1' => ' does John usually do' ,
      'option2' => 'do John usually does' ,
      'option3' => 'John usually does' ,
      'option4' => 'does John usually',
      'answer' => 'option1',
   ],
   [
      'id' => 6 ,
      'question' => 'This problem __________ by your brother yesterday' ,
      'option1' => 'Was solved' ,
      'option2' => 'Is solved' ,
      'option3' => 'Will be solved' ,
      'option4' => 'Solves' ,
      'answer' => 'option1',
   ],
   [
      'id' => 7 ,
      'question' => 'Do you think its ________ rain tomorrow?' ,
      'option1' => 'going' ,
      'option2' => 'going to' ,
      'option3' => 'to' ,
      'option4' => 'will' ,
      'answer' => 'option2',
   ],
   [
       'id' => 8 ,
      'question'=> "Look at the helicopter _____ the air! It is pink!",
      'option1' => "in" ,
      'option2' =>  "up" ,
      'option3' =>  "on" ,
      'option4' =>  "at" ,
      'answer' => 'option1',
   ],
   [
      //answer are given
      'id' => 9 ,
      'question' => "Samuel bought some sweets from the shop, and he ate _______ them in 2 hours." ,
      'option1' => "none" ,
      'option2' => "both" ,
      'option3' => "all of" ,
      'option4' => "neither" ,
      'answer' => 'option3',
   ],
   [
      'id' => 10 ,
      'question' => "Yes, but _______ of them work. They are _______ broken." ,
      'option1' => "neither / none" ,
      'option2' => "all / both" ,
      'option3' => "both / neither" ,
      'option4' => "none /all" ,
      'answer' => 'option1',
   ],
   [
      'id' => 11 ,
      'question' => "Linda will invite _______ her neighbours over for dinner. She thinks there will be more than fifteen people." ,
      'option1' => "all of" ,
      'option2' => 'neither of' ,
      'option3' => 'both of' ,
      'option4' => 'none of' ,
      'answer' => 'option1',
   ],
   [
      'id' => 12 ,
      'question' => "Mary asked us how _____ after that plant and we suggested _____ some research on the Internet.",
      'option1' => "to look / to do" ,
      'option2' =>"looking / do" ,
      'option3' => "look / to do",
      'option4' =>"to look / doing",
      'answer' => 'option4',
   ],
   [
      'id' => 13 ,
      'question' => "He dislikes _____ colourful clothes. Nobody can make him _____ even a simple green pullover. He always wears black." ,
      'option1' => "wear / to wear" ,
      'option2' =>"to wear / wearing" ,
      'option3' => "wearing / wear" ,
      'option4' => 'wear / wearing' ,
      'answer' => 'option3',
   ],
   [
      'id' => 14 ,
      'question' => "I _____ tell the time when I was 8 years old, but now I can." ,
      'option1' => "can" ,
      'option2' => "couldn't" ,
      'option3' => "can't" ,
      'option4' => "could" ,
      'answer' => 'option2',
   ],
   [
      'id' => 15 ,
      'question' => "Margaret _____ speak Italian and English, so she _____ work with a translator in this project." ,
      'option1' => "needn't / mustn't" ,
      'option2' => "can't / couldn't" ,
      'option3' => "can / needn't" ,
      'option4' => "must / musn't" ,
      'answer' => 'option3',
   ],
   [
      'id' => 16 ,
      'question' => "She _____ smoke because she is pregnant and it is harmful to the baby." ,
      'option1' => "needn't" ,
      'option2' => "couldn't" ,
      'option3' => "mustn't" ,
      'option4' => "can" ,
      'answer' => 'option3',
   ],
   [
      'id' => 17 ,
      'question' => "Bob is 79. Valerie is 79, too, so she is _____ Bob." ,
      'option1' => "the oldest" ,
      'option2' => "not as old as" ,
      'option3' => "older then" ,
      'option4' => "as old as" ,
      'answer' => 'option4',
   ],
   [
      'id' => 18 ,
      'question' => "Alexander is 75 kilograms. Nick is 97 kilograms so Alexander is _____ Nick." ,
      'option1' => "as heavy as" ,
      'option2' => "the heaviest" ,
      'option3' => "not as heavy as" ,
      'option4' => "heavier than" ,
      'answer' => 'option3',
   ],
   [
      'id' => 19 ,
      'question' => "We can win the game. They can win the game, too, because they are _____ us." ,
      'option1' => "strong" ,
      'option2' => "as strong as" ,
      'option3' => "stronger" ,
      'option4' => "the strong" ,
      'answer' => 'option2',
   ],
   [
      'id' => 20 ,
      'question' => "Ian _____ classes next week because he _____ to another town with the baseball team" ,
      'option1' => "is going to attend / will travel" ,
      'option2' => "won't attend / is travelling" ,
      'option3' => "isn't attending / won't travel" ,
      'option4' => "will attend / will travel" ,
      'answer' => 'option2',
   ],
   [
      'id' => 21 ,
      'question' => "She _____ his aunt in Egypt next month. She has already organized the trip. She thinks they _____ a great time together." ,
      'option1' => "will visit / are having" ,
      'option2' => "has visited / are going to have" ,
      'option3' => "is visiting / will have" ,
      'option4' => "is going to visit / have" ,
      'answer' => 'option3',
   ],
   [
      'id' => 22 ,
      'question' => "Don't come home late, or I _____ you go out with your friends again." ,
      'option1' => "am not letting" ,
      'option2' => "don't let" ,
      'option3' => "am not going to let" ,
      'option4' => "won't let" ,
      'answer' => 'option4',
   ],
   [
      'id' => 23 ,
      'question' => "Save some money for the future, or you _____ difficulty when you are old." ,
      'option1' => "iis going to have" ,
      'option2' => "have had" ,
      'option3' => "will have" ,
      'option4' => "are having" ,
      'answer' => 'option3',
   ],
   [
      'id' => 24 ,
      'question' => "Ian _____ classes next week because he _____ to another town with the baseball team" ,
      'option1' => "is going to attend / will travel" ,
      'option2' => "won't attend / is travelling" ,
      'option3' => "isn't attending / won't travel" ,
      'option4' => "will attend / will travel" ,
      'answer' => 'option2',
   ],
   // [
   //    'id' => 25 ,
   //    'question' => "There aren't ______ students on the campus today." ,
   //    'option1' => "a little" ,
   //    'option2' => "few" ,
   //    'option3' => "isn't attending / won't travel" ,
   //    'option4' => "will attend / will travel" ,
   //    'answer' => 'option2',
   // ],
   [
      'id' => 26 ,
      'question' => "He _____ a sweatsuit because he _____ to work today. He can have a rest at home." ,
      'option1' => "is wearing / isn't going" ,
      'option2' => "isn't wearing / is going" ,
      'option3' => "are wearing / aren't going" ,
      'option4' => "aren't wearing / are going" ,
      'answer' => 'option1',
   ],
   [
      'id' => 27 ,
      'question' => "Janice and I are at the mall now. We _____ some clothes for our children" ,
      'option1' => "isn't buying" ,
      'option2' => "am buying" ,
      'option3' => "is buying " ,
      'option4' => "are buying" ,
      'answer' => 'option4',
   ],
   [
      'id' => 28 ,
      'question' => "She can help _____ with the project, but her mother is ill and she is staying with _____ at the hospital nowadays." ,
      'option1' => "me / hers" ,
      'option2' => "our / her" ,
      'option3' => "us / her" ,
      'option4' => "ours / she" ,
      'answer' => 'option3 ',
   ],
   [
      'id' => 29 ,
      'question' => "_____ here. I want to show you something, but _____ mum. It is a secret" ,
      'option1' => "You are coming / you can tell" ,
      'option2' => "Don't come / tell" ,
      'option3' => "You can come / you are telling" ,
      'option4' => "Come / don't tell" ,
      'answer' => 'option4',
   ],
   [
      'id' => 30 ,
      'question' => "Please, _____ food to the bear. He is very aggressive and can bite _____." ,
      'option1' => "can give / us" ,
      'option2' => "give / its" ,
      'option3' => "can't give / them" ,
      'option4' => "don't give / you" ,
      'answer' => 'option4',
   ],
);
?>

